# Use the official Python image from the Docker Hub
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app


COPY requirements.txt .

# Install FastAPI and Uvicorn
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install fastapi uvicorn tensorflow numpy
# Make sure the data directory exists
RUN mkdir -p /data

# Expose port 80 for the application
EXPOSE 8080

# Define environment variable
ENV DATA_DIR=/data

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
